Formatted imports and fixed LDAP AUTH issue
Set the cn to be admin and do a simple_bind_s on the connection object.
Without this change the security API is not able to modify LDAP objects.

Error was encountered:
---------------------
Error: {'info': 'modifications require authentication', 'desc': 'Strong(er) authentication required'}
Error while creating Virtue for role firefox1231550177342:
Traceback (most recent call last):
  File "/home/ubuntu/galahad/excalibur/website/controller.py", line 304, in run
    self.virtue_id, config)
  File "/home/ubuntu/galahad/excalibur/website/apiendpoint_security.py", line 161, in transducer_enable
    True)
  File "/home/ubuntu/galahad/excalibur/website/apiendpoint_security.py", line 386, in __enable_disable
    'OpenLDAPvirtue', True)
  File "/home/ubuntu/galahad/excalibur/website/ldaplookup.py", line 165, in modify_obj
    raise e
STRONG_AUTH_REQUIRED: {'info': 'modifications require authentication',
'desc': 'Strong(er) authentication required'}